### ISSUE TITLE
discretization in grating

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#10]
In grating script there is a discretization parameter dx (40 nm in the provided example). But after optimization the size of elements and spacing is given with much higher precision (like 10^(-13) of nm), instead of being a multiple of dx. How can it be?
Another thing: the device Si thickness (220 nm in the example), should it be a multiple of dx?

**Comment by ludi1001** [comment]
No, the values do not have to multiples of dx because we employ permittivity averaging. If you look carefully, even in the discrete case the pixels aren't exactly discrete. In those cases, the grating edge is in between two pixels. Likewise, the thickness need not be a multiple of dx.

Internally, the implementation is relying on double-precision numbers, resulting in very high precision locations. Of course, such precision isn't necessary because the physics won't really change on those scales.

**Comment by LumiereWuChu** [comment]
> Hello, can you tell me which part of the code implements the problem of not being able to fully discretize at the boundary, and can I modify this part so that the simulation has a fully binary effect without the transition of the dielectric constant? 
I am currently designing a device with a relatively small feature size and this part of the dielectric constant is causing me a lot of errors, making it impossible to import gds for verification in lumerical.Thank you！
