### ISSUE TITLE
grating example - why first gap is fixed?

### ISSUE THREAD

**Issue by VovaZen** [stanfordnqp/spins-b#14]
I am wondering, why in all my optimizations the first gap (i.e., between waveguide and first grating element) is fixed and equals 2*minimum feature size (i.e., 200 nm for default feature size of 100 nm)? It might be first guess for the gap, but it never happens to be changed, even after 300 iterations...

**Comment by VovaZen** [comment]
I take this value from Logan's script to extract grating coordinates, and according to other issues, the beginning of the waveguide might not be at 0, therefore the first gap might not be fixed...

**Comment by ludi1001** [comment]
Implementation convenience. For simplicity, the fabrication constraint is imposing it for very technical reasons. It arises because grating parametrization currently has no idea where the waveguide starts, so the only way to ensure minimum feature size is satisfied is to actually ensure that the edge at least 2*dx away.

The simple way of avoiding this issue *most* of the time is just to invert the grating parametrization so that the first edge is falling edge instead of a rising edge. The most accurate solution is to actually pass in information about the surroundings into the creation of the grating parametrization. We'll implement the former for now as it's easier and should cover most use cases.

**Comment by VovaZen** [comment]
You are right regarding waveguide edge - please see my comments in #11. Also this is linked to #14.
